
api:
  env:
    - name: GRAVITEE_PLUGINS_PATH_0
      value: ${gravitee.home}/plugins
    - name: GRAVITEE_PLUGINS_PATH_1
      value: ${gravitee.home}/plugins-ext
  extraInitContainers: |
    - name: get-jdbc-plugin
      image: 'alpine'
      command: ['sh', '-c', "mkdir -p /tmp/plugins && wget -O /tmp/plugins/gravitee-repository-jdbc-3.1.1.zip https://download.gravitee.io/graviteeio-apim/plugins/repositories/gravitee-repository-jdbc/gravitee-repository-jdbc-3.1.1.zip"]
      volumeMounts:
        - name: graviteeio-apim-plugins
          mountPath: /tmp/plugins
    - name: get-jdbc-driver
      image: 'alpine'
      command: ['sh', '-c', "mkdir -p /tmp/jdbc && wget -O /tmp/jdbc/postgresql-42.2.16.jar https://jdbc.postgresql.org/download/postgresql-42.2.16.jar "]
      volumeMounts:
        - name: graviteeio-apim-jdbc-driver
          mountPath: /tmp/jdbc
  extraVolumeMounts: |
    - name: graviteeio-apim-plugins
      mountPath: /opt/graviteeio-management-api/plugins-ext
    - name: graviteeio-apim-jdbc-driver
      mountPath: /opt/graviteeio-management-api/plugins/ext/repository-jdbc
  extraVolumes: |
    - name: graviteeio-apim-plugins
      emptyDir: {}
    - name: graviteeio-apim-jdbc-driver
      emptyDir: {}

gateway:
  env:
    - name: GRAVITEE_PLUGINS_PATH_0
      value: ${gravitee.home}/plugins
    - name: GRAVITEE_PLUGINS_PATH_1
      value: ${gravitee.home}/plugins-ext
  extraInitContainers: |
    - name: get-jdbc-plugin
      image: 'alpine'
      command: ['sh', '-c', "mkdir -p /tmp/plugins && wget -O /tmp/plugins/gravitee-repository-jdbc-3.1.1.zip https://download.gravitee.io/graviteeio-apim/plugins/repositories/gravitee-repository-jdbc/gravitee-repository-jdbc-3.1.1.zip"]
      volumeMounts:
        - name: graviteeio-apim-plugins
          mountPath: /tmp/plugins
    - name: get-jdbc-driver
      image: 'alpine'
      command: ['sh', '-c', "mkdir -p /tmp/jdbc && wget -O /tmp/jdbc/postgresql-42.2.16.jar https://jdbc.postgresql.org/download/postgresql-42.2.16.jar "]
      volumeMounts:
        - name: graviteeio-apim-jdbc-driver
          mountPath: /tmp/jdbc
  extraVolumeMounts: |
    - name: graviteeio-apim-plugins
      mountPath: /opt/graviteeio-gateway/plugins-ext
    - name: graviteeio-apim-jdbc-driver
      mountPath: /opt/graviteeio-gateway/plugins/ext/repository-jdbc
  extraVolumes: |
    - name: graviteeio-apim-plugins
      emptyDir: {}
    - name: graviteeio-apim-jdbc-driver
      emptyDir: {}