{{- if .Values.portal.enabled -}}
{{- if .Values.portal.ingress.enabled -}}
{{- $serviceAPIName := include "gravitee.portal.fullname" . -}}
{{- $serviceAPIPort := .Values.portal.service.externalPort -}}
{{- $ingressPath   := .Values.portal.ingress.path -}}
{{- $apiVersion := include "ingress.apiVersion" . -}}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ template "gravitee.portal.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "{{ .Values.portal.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    {{- range $key, $value := .Values.portal.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  {{- range $host := .Values.portal.ingress.hosts }}
  {{- if (eq $apiVersion "networking.k8s.io/v1") }}
  - host: {{ $host }}
    http:
      paths:
        - pathType: Prefix
          path: {{ $ingressPath }}
          backend:
            service:
              name: {{ $serviceAPIName }}
              port:
                number: {{ $serviceAPIPort }}
  {{ else }}
  - host: {{ $host }}
    http:
      paths:
        - path: {{ $ingressPath }}
          backend:
            serviceName: {{ $serviceAPIName }}
            servicePort: {{ $serviceAPIPort }}
  {{- end -}}
  {{- end -}}
  {{- if .Values.portal.ingress.tls }}
  tls:
{{ toYaml .Values.portal.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}
