{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gravitee.ui.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "{{ .Values.ui.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  use-gzip: "true"
  gzip-level: "5"
  gzip-types: "*"
  constants.json: |
    {
      {{- if .Values.ui.baseURL }}
      "baseURL": "{{ .Values.ui.baseURL }}",
      {{- else }}
      "baseURL": "https://{{ index .Values.ui.ingress.hosts 0 }}{{ .Values.ui.ingress.path }}/management",
      {{- end }}
    }
{{- end -}}
