{{- if .Values.gateway.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gravitee.gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "{{ .Values.gateway.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  gravitee.yml: |
    # Gateway HTTP server
    http:
      port: 8082
      host: 0.0.0.0
      # idleTimeout: 0
      # tcpKeepAlive: true
      # compressionSupported: false
      # instances: 0
      alpn: true
      {{- if .Values.gateway.ssl.enabled }}
      secured: true
      ssl:
        keystore:
          path: {{ .Values.gateway.ssl.keystore.path }}
          password: {{ .Values.gateway.ssl.keystore.password | quote }}
        clientAuth: {{ .Values.gateway.ssl.clientAuth }}
        {{- if .Values.gateway.ssl.truststore }}
        truststore:
          path: {{ .Values.gateway.ssl.truststore.path }}
          password: {{ .Values.gateway.ssl.truststore.password | quote }}
        {{- end }}
      {{- end }}
      websocket:
        enabled: {{ .Values.gateway.websocket }}  
    management:
      {{- if .Values.gateway.management.http.enabled }}
      type: http
      http:
        url: {{ .Values.gateway.management.http.url }}
        keepAlive: true
        idleTimeout: 30000
        connectTimeout: 10000
        authentication:
          basic:
            username: {{ .Values.gateway.management.http.username }}
            password: {{ .Values.gateway.management.http.password }}
      {{- end }}
      {{- if .Values.gateway.management.mongo.enabled }}
      type: mongodb
      mongodb:
        {{- if .Values.mongo.uri }}
        uri: {{ .Values.mongo.uri }}
        {{ else }}
        uri: mongodb://{{- if (eq .Values.mongo.auth.enabled true) }}{{ .Values.mongo.auth.username }}:{{ .Values.mongo.auth.password }}@{{- end }}{{ .Values.mongo.dbhost }}:{{ .Values.mongo.dbport }}/{{ .Values.mongo.dbname }}?{{- if .Values.mongo.rsEnabled }}&replicaSet={{ .Values.mongo.rs }}{{- end }}{{- if (eq .Values.mongo.auth.enabled true) }}&authSource={{ .Values.mongo.auth.source }}{{- end }}{{- if .Values.mongo.connectTimeoutMS }}&connectTimeoutMS={{ .Values.mongo.connectTimeoutMS }}{{- end }}
        {{- end }}
      {{- end }}
    ratelimit:
      {{- if .Values.gateway.ratelimit.mongo.enabled }}
      type: mongodb
      mongodb:
        {{- if .Values.mongo.uri }}
        uri: {{ .Values.mongo.uri }}
        {{ else }}
        uri: mongodb://{{- if (eq .Values.mongo.auth.enabled true) }}{{ .Values.mongo.auth.username }}:{{ .Values.mongo.auth.password }}@{{- end }}{{ .Values.mongo.dbhost }}:{{ .Values.mongo.dbport }}/{{ .Values.mongo.dbname }}?{{- if .Values.mongo.rsEnabled }}&replicaSet={{ .Values.mongo.rs }}{{- end }}{{- if (eq .Values.mongo.auth.enabled true) }}&authSource={{ .Values.mongo.auth.source }}{{- end }}{{- if .Values.mongo.connectTimeoutMS }}&connectTimeoutMS={{ .Values.mongo.connectTimeoutMS }}{{- end }}
        {{- end }}
      {{- end }}
      {{- if .Values.gateway.ratelimit.redis.enabled }}
      type: redis
      redis:
        host: {{ .Values.gateway.ratelimit.redis.host }}
        port: {{ .Values.gateway.ratelimit.redis.port }}
      {{- end }}
    cache:
      type: ehcache
      enabled: true

    # Sharding tags configuration
    # Allows to define inclusion/exclusion sharding tags to only deploy a part of APIs. To exclude just prefix the tag with '!'.
    tags: {{ .Values.gateway.sharding_tags }}  

    # Multi-tenant configuration
    # Allow only a single-value
    tenant: {{ .Values.gateway.tenant }}  

    # Reporters configuration (used to store reporting monitoring data, request metrics, healthchecks and others...
    # All reporters are enabled by default. To stop one of them, you have to add the property 'enabled: false'
    reporters:
      # Elasticsearch reporter
      elasticsearch:
        enabled: true # Is the reporter enabled or not (default to true)
        {{- with .Values.es.endpoints }}
        endpoints:
          {{ toYaml . | nindent 10 | trim -}}
        {{- end }}
        {{- if (eq .Values.es.security.enabled true) }}
        security:
          username: {{ .Values.es.security.username }}
          password: {{ .Values.es.security.password }}
        {{- end }}
        {{- if (eq .Values.es.ssl.enabled true) }}
        ssl:
          keystore:
            type: {{ .Values.es.ssl.keystore.type }}
            {{- if or .Values.es.ssl.keystore.path .Values.es.ssl.keystore.password }}
            path: {{ .Values.es.ssl.keystore.path }}
            password: {{ .Values.es.ssl.keystore.password }}
            {{- end }}
            {{- if or .Values.es.ssl.keystore.certs .Values.es.ssl.keystore.keys }}
            certs: {{ .Values.es.ssl.keystore.certs }}
            keys: {{ .Values.es.ssl.keystore.keys }}
            {{- end }}
        {{- end }}
        index: {{ .Values.es.index }}
        bulk:
          actions: 1000           # Number of requests action before flush
          flush_interval: 5       # Flush interval in seconds
        {{- if (eq .Values.es.ingest_plugin true) }}
        pipeline:
          plugins:
            ingest: gravitee
        {{- end }}
    services:
      core:
        http:
          port: 18082
          host: localhost
          authentication:
            # authentication type to be used for the core services
            # - none : to disable authentication
            # - basic : to use basic authentication
            # default is "basic"
            type: basic
            users:
              admin: adminadmin
      # Synchronization daemon used to keep the gateway state in sync with the configuration from the management repository
      # Be aware that, by disabling it, the gateway will not be sync with the configuration done through management API
      # and management UI
      sync:
        # Synchronization is done each 5 seconds
        cron: '*/5 * * * * *'

      # Service used to store and cache api-keys from the management repository to avoid direct repository communication
      # while serving requests.
      apikeyscache:
        delay: 10000
        unit: MILLISECONDS
        threads: 3 # Threads core size used to retrieve api-keys from repository.

      # Local registry service.
      # This registry is used to load API Definition with json format from the file system. By doing so, you do not need
      # to configure your API using the web console or the rest API (but you need to know and understand the json descriptor
      # format to make it work....)
      local:
        enabled: false
        path: ${gravitee.home}/apis # The path to API descriptors

      # Gateway monitoring service.
      # This service retrieves metrics like os / process / jvm metrics and send them to an underlying reporting service.
      monitoring:
        delay: 5000
        unit: MILLISECONDS

      # Endpoint healthcheck service.
      healthcheck:
        threads: 3 # Threads core size used to check endpoint availability
      {{- if .Values.gateway.services.bridge.enabled }}
      bridge:
        http:
          enabled: true
          port: 18092
          host: 0.0.0.0
          authentication:
            type: basic
            users:
              {{ .Values.gateway.services.bridge.username }}: {{ .Values.gateway.services.bridge.password }}
      {{- end }}
    handlers:
      request:
        transaction:
          header: X-Gravitee-Transaction-Id
    
    # Customize the api-key header and / or query parameter.
    policy:
      api-key:
        header: {{ .Values.gateway.apiKey.header }}
        param: {{ .Values.gateway.apiKey.param }}
  {{- if .Values.gateway.logging.debug }}
  logback.xml: |
    <?xml version="1.0" encoding="UTF-8"?>

    <!--
      ~ Copyright (c) 2015-2016, The Gravitee team (http://www.gravitee.io)
      ~
      ~  Licensed under the Apache License, Version 2.0 (the "License");
      ~  you may not use this file except in compliance with the License.
      ~  You may obtain a copy of the License at
      ~
      ~  http://www.apache.org/licenses/LICENSE-2.0
      ~
      ~  Unless required by applicable law or agreed to in writing, software
      ~  distributed under the License is distributed on an "AS IS" BASIS,
      ~  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      ~  See the License for the specific language governing permissions and
      ~  limitations under the License.
      -->

    <configuration>

        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <!-- encoders are assigned the type
                ch.qos.logback.classic.encoder.PatternLayoutEncoder by default -->
            <encoder>
                <pattern>{{ .Values.gateway.logging.stdout.encoderPattern }}</pattern>
            </encoder>
        </appender>

        {{- if .Values.gateway.logging.file.enabled }}
        <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
            <file>${gravitee.home}/logs/gravitee.log</file>
{{ .Values.gateway.logging.file.rollingPolicy | indent 16 }}
            <encoder>
                <pattern>{{ .Values.gateway.logging.file.encoderPattern }}</pattern>
            </encoder>
        </appender>
        {{- end }}

        {{- if .Values.gateway.logging.file.enabled }}
        <appender name="async-file" class="ch.qos.logback.classic.AsyncAppender">
            <appender-ref ref="FILE" />
        </appender>
        {{- end }}

        <appender name="async-console" class="ch.qos.logback.classic.AsyncAppender">
            <appender-ref ref="STDOUT" />
        </appender>

        <logger name="io.gravitee" level="{{ .Values.gateway.logging.graviteeLevel }}" />
        <logger name="org.reflections" level="WARN" />
        <logger name="org.springframework" level="WARN" />
        <logger name="org.eclipse.jetty" level="{{ .Values.gateway.logging.jettyLevel }}" />

        <!-- Strictly speaking, the level attribute is not necessary since -->
        <!-- the level of the root level is set to DEBUG by default.       -->
        <root level="INFO">
            <appender-ref ref="async-console" />
            {{- if .Values.gateway.logging.file.enabled }}
            <appender-ref ref="async-file" />
            {{- end }}
        </root>

    </configuration>
  {{- end -}}
  {{- end -}}
