{{- if .Values.ui.enabled -}}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "gravitee.ui.fullname" . }}
  labels:
    app: {{ template "gravitee.name" . }}
    component: "{{ .Values.ui.name }}"
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ template "gravitee.name" . }}
      component: "{{ .Values.ui.name }}"
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "{{ .Values.chaos.enabled }}"
        checksum/config: {{ include (print $.Template.BasePath "/ui-configmap.yaml") . | sha256sum }}
      labels:
        app: {{ template "gravitee.name" . }}
        component: "{{ .Values.ui.name }}"
        release: {{ .Release.Name }}
    spec:
    {{- if .Values.ui.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.ui.nodeSelector | indent 8 }}
    {{- end }}
      containers:
        - name: {{ template "gravitee.ui.fullname" . }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          env:
            - name: MGMT_API_URL
              value: "https://{{index .Values.api.ingress.hosts 0 }}{{ .Values.api.ingress.path }}"
            - name: MGMT_UI_URL
              value: "https://{{index .Values.ui.ingress.hosts 0 }}"
          ports:
            - containerPort: {{ .Values.ui.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.ui.service.internalPort }}
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.ui.service.internalPort }}
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
{{ toYaml .Values.ui.resources | indent 12 }}
          volumeMounts:
            - name: config
              mountPath: /var/www/html/constants.json
              subPath: constants.json
      {{- if .Values.ui.image.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.ui.image.pullSecrets }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "gravitee.ui.fullname" . }}
      {{- range .Values.ui.extraVolumeMounts }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ .existingClaim }}
      {{- end }}
{{- end -}}