{{- if .Values.gateway.enabled -}}
{{- if .Values.gateway.services.bridge.enabled -}}
{{- if .Values.gateway.services.bridge.ingress.enabled -}}
{{- $serviceGWName := include "gravitee.gateway.fullname" . -}}
{{- $serviceGWPort := .Values.gateway.services.bridge.service.externalPort -}}
{{- $ingressPath   := .Values.gateway.services.bridge.ingress.path -}}
{{- $apiVersion := include "ingress.apiVersion" . -}}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ template "gravitee.gateway.fullname" . }}-bridge
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "{{ .Values.gateway.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    {{- range $key, $value := .Values.gateway.services.bridge.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  {{- range $host := .Values.gateway.services.bridge.ingress.hosts }}
  {{- if (eq $apiVersion "networking.k8s.io/v1") }}
  - host: {{ $host }}
    http:
      paths:
        - pathType: Prefix
          path: {{ $ingressPath }}
          backend:
            service:
              name: {{ $serviceGWName }}
              port:
                number: {{ $serviceGWPort }}
  {{ else }} # Just for backward compatibility, K8S < 1.19
  - host: {{ $host }}
    http:
      paths:
        - path: {{ $ingressPath }}
          backend:
            serviceName: {{ $serviceGWName }}
            servicePort: {{ $serviceGWPort }}
  {{- end -}}
  {{- end -}}
  {{- if .Values.gateway.services.bridge.ingress.tls }}
  tls:
{{ toYaml .Values.gateway.services.bridge.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}