{{- if .Values.gateway.services.core.http.enabled -}}
{{- if .Values.gateway.services.core.ingress.enabled -}}
{{- $serviceAPIName := include "gravitee.gateway.fullname" . -}}
{{- $serviceAPIPort := .Values.gateway.services.core.service.externalPort -}}
{{- $ingressPath   := .Values.gateway.services.core.ingress.path -}}
{{- $apiVersion := include "ingress.apiVersion" . -}}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ template "gravitee.gateway.fullname" . }}-technical
  labels:
    app.kubernetes.io/app: {{ template "gravitee.name" . }}
    app.kubernetes.io/component: "{{ .Values.gateway.name }}"
    app.kubernetes.io/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.gateway.services.core.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  {{- range $host := .Values.gateway.services.core.ingress.hosts }}
  {{- if (eq $apiVersion "networking.k8s.io/v1") }}
  - host: {{ $host }}
    http:
      paths:
      - pathType: Prefix
        path: {{ $ingressPath }}
        backend:
          {{- if (eq $apiVersion "networking.k8s.io/v1") }}
          service:
            name: {{ $serviceAPIName }}
            port:
              number: {{ $serviceAPIPort }}
          {{ else }}
          serviceName: {{ $serviceAPIName }}
          servicePort: {{ $serviceAPIPort }}
          {{- end -}}
  {{- end -}}
  {{- if .Values.gateway.services.core.ingress.tls }}
  tls:
{{ toYaml .Values.gateway.services.core.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}
