{{- if .Values.api.enabled -}}
{{- if .Values.api.ingress.enabled -}}
{{- $serviceAPIName := include "gravitee.api.fullname" . -}}
{{- $serviceAPIPort := .Values.api.service.externalPort -}}
{{- $ingressPath   := .Values.api.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "gravitee.api.fullname" . }}
  labels:
    app: {{ template "gravitee.name" . }}
    component: "{{ .Values.api.name }}"
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.api.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- if .Values.api.ingress.rules -}}
    {{ toYaml .Values.api.ingress.rules | indent 6 }}
    {{- end -}}
    {{- range $host := .Values.api.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $serviceAPIName }}
              servicePort: {{ $serviceAPIPort }}
    {{- end -}}
  {{- if .Values.api.ingress.tls }}
  tls:
{{ toYaml .Values.api.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}