{{- if .Values.ui.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "gravitee.name" . }}
    component: "{{ .Values.ui.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "gravitee.ui.fullname" . }}
data:
  use-gzip: "true"
  gzip-level: "5"
  gzip-types: "*"
  constants.json: |
    {
      "baseURL": "https://{{ index .Values.api.ingress.hosts 0 }}/management/",
      "management": {
        "title": "{{ .Values.ui.managementTitle }}"
      },
      "documentation": {
        "url": "{{ .Values.ui.documentationLink }}"
      },
      "portal": {
        "entrypoint": "https://{{ index .Values.gateway.ingress.hosts 0 }}/gateway",
        "title": "{{ .Values.ui.title }}"
        {{- if .Values.ui.portal }}
          {{- range $key, $value := .Values.ui.portal }},
          "{{ $key }}": {{ toJson $value }}
          {{- end -}}
        {{- end }}
      }
      {{- if .Values.ui.theme }},
      "theme": {{ toJson .Values.ui.theme }}
      {{- end }}
      {{- if .Values.ui.scheduler }},
      "scheduler": {{ toJson .Values.ui.scheduler }}
      {{- end }}
    }
{{- end -}}