{{- if .Values.gateway.enabled -}}
{{- if .Values.gateway.ingress.enabled -}}
{{- $serviceGWName := include "gravitee.gateway.fullname" . -}}
{{- $serviceGWPort := .Values.gateway.service.externalPort -}}
{{- $ingressPath   := .Values.gateway.ingress.path -}}
{{- $ingressPathType   := .Values.api.ingress.pathType | default "Prefix" -}}
apiVersion: {{ template "ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "gravitee.gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "gravitee.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: "{{ .Values.gateway.name }}"
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  annotations:
    {{- range $key, $value := .Values.gateway.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $host := .Values.gateway.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: {{ $ingressPath }}
            {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ $ingressPathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $serviceGWName }}
                port:
                  number: {{ $serviceGWPort }}
              {{- else }}
              serviceName: {{ $serviceGWName }}
              servicePort: {{ $serviceGWPort }}
              {{- end }}
    {{- end -}}
  {{- if .Values.gateway.ingress.tls }}
  tls:
{{ toYaml .Values.gateway.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}
